import SkillsBuilderGetters from "./getters";

export default {
  state: {
    skillsBuilder: {
      Languages: [
        {
          id: 1,
          name: "HTML",
          level: 5,
          img: "html.png",
          desc: "HTML is a markup language for creating web pages and web applications. With Cascading Style Sheets (CSS) and JavaScript, it forms a triad of cornerstone technologies for the World Wide Web.",
        },
        {
          id: 2,
          name: "CSS",
          level: 5,
          img: "css.png",
          desc: "Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language like HTML. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.",
        },
        {
          id: 3,
          name: "JavaScript",
          type: "Languages",
          level: 5,
          img: "js.png",
          desc: "JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm.",
        },
        {
          id: 4,
          name: "TypeScript",
          type: "Languages",
          level: 4,
          img: "ts.png",
          desc: "TypeScript is an open-source programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript, and adds optional static typing to the language.",
        },
        {
          id: 5,
          name: "Java",
          level: 3,
          img: "java.png",
          desc: "Java is a general-purpose computer-programming language that is concurrent, class-based, object-oriented, and specifically designed to have as few implementation dependencies as possible.",
        },
        {
          id: 6,
          name: "C#",
          level: 3,
          img: "csharp.png",
          desc: "C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines.",
        },
        {
          id: 7,
          name: "C++",
          level: 3,
          img: "cpp.png",
          desc: "C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language, or 'C with Classes'.",
        },
        {
          id: 8,
          name: "Python",
          level: 3,
          img: "python.png",
          desc: "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.",
        },
      ],
      Frameworks: [
        {
          id: 1,
          name: "Vue",
          type: "Frontend",
          level: 5,
          img: "vue.png",
          desc: "Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members.",
        },
        {
          id: 2,
          name: "Svelte",
          type: "Frontend",
          level: 4,
          img: "svelte.png",
          desc: "Svelte is a JavaScript framework for building user interfaces. It is a compiler that takes your declarative components and converts them into efficient JavaScript that surgically updates the DOM.",
        },
        {
          id: 3,
          name: "React",
          type: "Frontend",
          level: 3,
          img: "react.png",
          desc: "React is an open-source, front end, JavaScript library for building user interfaces or UI components. It is maintained by Facebook and a community of individual developers and companies.",
        },
        {
          id: 4,
          name: "Express",
          type: "Backend",
          level: 5,
          img: "express.png",
          desc: "Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.",
        },
        {
          id: 5,
          name: "Node",
          type: "Backend",
          level: 5,
          img: "node.png",
          desc: "Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.",
        },
        {
          id: 6,
          name: "Nest",
          type: "Backend",
          level: 4,
          img: "nest.png",
          desc: "Nest (NestJS) is a framework for building efficient, scalable Node.js server-side applications. It uses progressive JavaScript, is built with and fully supports TypeScript (yet still enables developers to code in pure JavaScript) and combines elements of OOP (Object Oriented Progamming), FP (Functional Programming), and FRP (Functional Reactive Programming).",
        },
        {
          id: 7,
          name: "Nuxt",
          type: "Backend",
          level: 4,
          img: "nuxt.png",
          desc: "Nuxt.js is an open source JavaScript framework based on Vue.js universal application framework. It is used for creating Vue.js based web applications that can run on the server side as well as the client side.",
        },
        {
          id: 8,
          name: "Ionic",
          type: "Mobile",
          level: 4,
          img: "ionic.png",
          desc: "Ionic is an open-source mobile app development framework created by Max Lynch, Ben Sperry, and Adam Bradley of Drifty Co. It is based on Angular and Apache Cordova.",
        },
        {
          id: 9,
          name: "Cordova",
          type: "Mobile",
          level: 4,
          img: "cordova.png",
          desc: "Apache Cordova is a mobile application development framework originally created by Nitobi. It is maintained by the Apache Software Foundation and is available under the Apache 2.0 license.",
        },
        {
          id: 10,
          name: "Electron",
          type: "Desktop",
          level: 4,
          img: "electron.png",
          desc: "Electron is an open-source software framework developed and maintained by GitHub. It allows for the development of desktop GUI applications using web technologies: it combines the Chromium rendering engine and the Node.js runtime.",
        },
        {
          id: 11,
          name: "QT",
          type: "Desktop",
          level: 3,
          img: "qt.png",
          desc: "Qt is a cross-platform application framework that is used for developing application software that can be run on various software and hardware platforms with little or no change in the underlying codebase, while still being a native application with native capabilities and speed.",
        },
        {
          id: 12,
          name: "KOA",
          type: "Backend",
          level: 3,
          img: "koa.png",
          desc: "Koa is a new web framework designed by the team behind Express, which aims to be a smaller, more expressive, and more robust foundation for web applications and APIs.",
        },
        {
          id: 13,
          name: "ASP.NET",
          type: "Backend",
          level: 3,
          img: "aspnet.png",
          desc: "ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript. ASP.NET is open source and is licensed under the Apache License, Version 2.0.",
        },
      ],
      Libraries: [
        {
          id: 1,
          name: "Bootstrap",
          level: 5,
          img: "bootstrap.png",
          desc: "Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains CSS- and (optionally) JavaScript-based design templates for typography, forms, buttons, navigation and other interface components.",
        },
        {
          id: 2,
          name: "Tailwind",
          level: 4,
          img: "tailwind.png",
          desc: "Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces. It is a highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override.",
        },
        {
          id: 3,
          name: "Vuetify",
          level: 4,
          img: "vuetify.png",
          desc: "Vuetify is a semantic component framework for Vue. It aims to provide clean, semantic and reusable components that make building your application a breeze.",
        },
        {
          id: 4,
          name: "Bulma",
          level: 4,
          img: "bulma.png",
          desc: "Bulma is a free, open source CSS framework based on Flexbox and used by more than 100,000 developers. Bulma provides a modern framework with built-in responsiveness and several optional JavaScript extensions.",
        },
      ],
      Databases: [
        {
          id: 1,
          name: "SQL Server",
          level: 5,
          img: "sqlserver.png",
          desc: "Microsoft SQL Server is a relational database management system developed by Microsoft. As a database server, it is a software product with the primary function of storing and retrieving data as requested by other software applications—which may run either on the same computer or on another computer across a network (including the Internet).",
        },
        {
          id: 2,
          name: "MySQL",
          level: 5,
          img: "mysql.png",
          desc: "MySQL is an open-source relational database management system (RDBMS). Its name is a combination of 'My', the name of co-founder Michael Widenius's daughter, and 'SQL', the abbreviation for Structured Query Language.",
        },
        {
          id: 3,
          name: "MongoDB",
          level: 4,
          img: "mongodb.png",
          desc: "MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas.",
        },
        {
          id: 4,
          name: "PostgreSQL",
          level: 4,
          img: "postgresql.png",
          desc: "PostgreSQL, also known as Postgres, is a free and open-source relational database management system emphasizing extensibility and SQL compliance. It was originally named POSTGRES, referring to its origins as a successor to the Ingres database developed at the University of California, Berkeley.",
        },
      ],
      Tools: [
        {
          id: 1,
          name: "Git",
          level: 5,
          img: "git.png",
          desc: "Git is a distributed version-control system for tracking changes in source code during software development. It is designed for coordinating work among programmers, but it can be used to track changes in any set of files. Its goals include speed, data integrity, and support for distributed, non-linear workflows.",
        },
        {
          id: 2,
          name: "Docker",
          level: 4,
          img: "docker.png",
          desc: "Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers. Containers are isolated from one another and bundle their own software, libraries and configuration files; they can communicate with each other through well-defined channels.",
        },
        {
          id: 3,
          name: "Gulp",
          level: 4,
          img: "gulp.png",
          desc: "Gulp is a toolkit for automating painful or time-consuming tasks in your development workflow, so you can stop messing around and build something.",
        },
        {
          id: 4,
          name: "Webpack",
          level: 4,
          img: "webpack.png",
          desc: "Webpack is a static module bundler for modern JavaScript applications. When webpack processes your application, it internally builds a dependency graph which maps every module your project needs and generates one or more bundles.",
        },
        {
          id: 5,
          name: "NPM",
          level: 4,
          img: "npm.png",
          desc: "npm is a package manager for the JavaScript programming language. It is the default package manager for the JavaScript runtime environment Node.js. It consists of a command line client, also called npm, and an online database of public and paid-for private packages, called the npm registry.",
        },
        {
          id: 6,
          name: "Yarn",
          level: 4,
          img: "yarn.png",
          desc: "Yarn is a package manager that doubles down as project manager. Whether you work on one-shot projects or large monorepos, as a hobbyist or an enterprise user, we've got you covered.",
        },
        {
          id: 7,
          name: "Vite",
          level: 4,
          img: "vite.png",
          desc: "Vite is a new breed of frontend build tool that significantly improves the frontend development experience. It consists of two major parts: a dev server that provides rich feature enhancements over native ES modules, and a build command that bundles your code with Rollup.",
        },
        {
          id: 8,
          name: "VS Code",
          level: 5,
          img: "vscode.png",
          desc: "Visual Studio Code is a source-code editor developed by Microsoft for Windows, Linux and macOS. Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git. Users can change the theme, keyboard shortcuts, preferences, and install extensions that add additional functionality.",
        },
        {
          id: 9,
          name: "Postman",
          level: 4,
          img: "postman.png",
          desc: "Postman is a collaboration platform for API development. Postman's features simplify each step of building an API and streamline collaboration so you can create better APIs—faster.",
        },
        {
          id: 10,
          name: "X-State",
          level: 4,
          img: "xstate.png",
          desc: "XState is a JavaScript library for modeling and implementing state machines and statecharts. It is a state management library that helps you manage state in your application. It is a library for managing state machines and statecharts in JavaScript.",
        },
        {
          id: 11,
          name: "Jest",
          level: 4,
          img: "jest.png",
          desc: "Jest is a delightful JavaScript Testing Framework with a focus on simplicity. It works with projects using: Babel, TypeScript, Node, React, Angular, Vue and more!",
        },
        {
          id: 12,
          name: "Cypress",
          level: 4,
          img: "cypress.png",
          desc: "Cypress is a front end testing tool built for the modern web. Cypress is fast, easy to use and reliable testing for anything that runs in a browser.",
        },
        {
          id: 13,
          name: "Froala",
          level: 4,
          img: "froala.png",
          desc: "Froala is a WYSIWYG HTML Editor that enables rich text editing capabilities for your applications. It is a JavaScript library that allows you to add a rich text editor to your website.",
        },
        {
          id: 14,
          name: "TipTap",
          level: 4,
          img: "tiptap.png",
          desc: "TipTap is a rich-text editor for Vue.js. It is a framework-agnostic rich-text editor for the web. It is a framework-agnostic rich-text editor for the web. It is a framework-agnostic rich-text editor for the web.",
        },
        {
          id: 15,
          name: "OpenCV",
          level: 4,
          img: "opencv.png",
          desc: "OpenCV (Open Source Computer Vision Library) is a library of programming functions mainly aimed at real-time computer vision. Originally developed by Intel, it was later supported by Willow Garage then Itseez (which was later acquired by Intel). The library is cross-platform and free for use under the open-source Apache 2 License.",
        },
        {
          id: 16,
          name: "Tensorflow",
          level: 4,
          img: "tensorflow.png",
          desc: "TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries, and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML-powered applications.",
        },
        {
          id: 17,
          name: "REST API",
          level: 4,
          img: "rest.png",
          desc: "A REST API is an application program interface (API) that uses HTTP requests to GET, PUT, POST and DELETE data. REST stands for REpresentational State Transfer. It is an architectural style and approach to communications often used in web services development.",
        },
      ],
      Cloud: [
        {
          id: 0,
          name: "AWS",
          level: 4,
          img: "aws.png",
          desc: "Amazon Web Services (AWS) is a subsidiary of Amazon that provides on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered pay-as-you-go basis. These cloud computing web services provide a variety of basic abstract technical infrastructure and distributed computing building blocks and tools.",
        },
        {
          id: 1,
          name: "Azure",
          level: 4,
          img: "azure.png",
          desc: "Microsoft Azure is a cloud computing service created by Microsoft for building, testing, deploying, and managing applications and services",
        },
      ],
    },
  },
  getters: SkillsBuilderGetters,
};
